[theme]
primaryColor="#cbaee6"
backgroundColor="white"
secondaryBackgroundColor="lightGray"
textColor="#042727"
font="monospace"


[server]
port = 7070
sslCertFile = './cert.pem'
sslKeyFile = './key.pem'